/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "myreg" *)
(* src = "src/myreg.v:2.1-20.10" *)
module \$paramod\myreg\N=s32'00000000000000000000000000000001 (d, q, clk, en, rst);
  (* src = "src/myreg.v:3.19-3.20" *)
  input [0:0] d;
  wire [0:0] d;
  (* src = "src/myreg.v:4.24-4.25" *)
  output [0:0] q;
  wire [0:0] q;
  (* src = "src/myreg.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "src/myreg.v:6.11-6.13" *)
  input en;
  wire en;
  (* src = "src/myreg.v:7.11-7.14" *)
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  (* src = "src/myreg.v:3.19-3.20" *)
  wire _02_;
  (* src = "src/myreg.v:6.11-6.13" *)
  wire _03_;
  (* src = "src/myreg.v:4.24-4.25" *)
  wire _04_;
  (* src = "src/myreg.v:7.11-7.14" *)
  wire _05_;
  wire _06_;
  wire _07_;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(_05_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(_04_),
    .A1(_02_),
    .S(_03_),
    .X(_01_)
  );
  (* src = "src/myreg.v:12.4-18.7" *)
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_07_),
    .Q(q),
    .RESET_B(_06_)
  );
  assign _04_ = q;
  assign _02_ = d;
  assign _03_ = en;
  assign _07_ = _01_;
  assign _05_ = rst;
  assign _06_ = _00_;
endmodule

(* top =  1  *)
(* src = "src/fpmul.v:2.1-69.10" *)
module fpmul(x1, x2, y, clk, rst, en, ready);
  (* src = "src/fpmul.v:3.18-3.20" *)
  input [15:0] x1;
  wire [15:0] x1;
  (* src = "src/fpmul.v:4.18-4.20" *)
  input [15:0] x2;
  wire [15:0] x2;
  (* src = "src/fpmul.v:5.19-5.20" *)
  output [15:0] y;
  wire [15:0] y;
  (* src = "src/fpmul.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "src/fpmul.v:7.11-7.14" *)
  input rst;
  wire rst;
  (* src = "src/fpmul.v:8.11-8.13" *)
  input en;
  wire en;
  (* src = "src/fpmul.v:9.12-9.17" *)
  output ready;
  wire ready;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0470_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0471_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0472_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0473_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0474_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0475_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0476_;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire _0477_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0478_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0479_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0480_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0481_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0482_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0483_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0484_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0485_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0486_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0487_;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  wire _0794_;
  wire _0795_;
  wire _0796_;
  wire _0797_;
  wire _0798_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0799_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0800_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0801_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0802_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0803_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0804_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0805_;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire _0806_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0807_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0808_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0809_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0810_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0811_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0812_;
  (* src = "src/fpmul.v:16.12-16.18" *)
  wire _0813_;
  (* src = "src/fpmul.v:13.6-13.9" *)
  wire _0814_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0815_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0816_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0817_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0818_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0819_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0820_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0821_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0822_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0823_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0824_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0825_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0826_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0827_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0828_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0829_;
  (* src = "src/fpmul.v:3.18-3.20" *)
  wire _0830_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0831_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0832_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0833_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0834_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0835_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0836_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0837_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0838_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0839_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0840_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0841_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0842_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0843_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0844_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0845_;
  (* src = "src/fpmul.v:4.18-4.20" *)
  wire _0846_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0847_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0848_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0849_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0850_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0851_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0852_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0853_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0854_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0855_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0856_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0857_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0858_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0859_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0860_;
  (* src = "src/fpmul.v:5.19-5.20" *)
  wire _0861_;
  (* src = "src/fpmul.v:21.6-21.10" *)
  wire end1;
  (* src = "src/fpmul.v:15.12-15.19" *)
  wire [7:0] exp_grs;
  (* src = "src/fpmul.v:17.13-17.21" *)
  wire [10:0] mant_grs;
  (* src = "src/fpmul.v:14.12-14.17" *)
  wire [7:0] p_exp;
  (* src = "src/fpmul.v:16.12-16.18" *)
  (* unused_bits = "7" *)
  wire [7:0] p_mant;
  (* src = "src/fpmul.v:13.6-13.9" *)
  wire p_s;
  (* src = "src/fpmul.v:20.13-20.19" *)
  wire [15:0] result;
  sky130_fd_sc_hd__clkinv_1 _0862_ (
    .A(_0815_),
    .Y(_0784_)
  );
  sky130_fd_sc_hd__clkinv_1 _0863_ (
    .A(_0831_),
    .Y(_0785_)
  );
  sky130_fd_sc_hd__xor2_1 _0864_ (
    .A(_0837_),
    .B(_0821_),
    .X(_0814_)
  );
  sky130_fd_sc_hd__and3_1 _0865_ (
    .A(_0843_),
    .B(_0825_),
    .C(_0824_),
    .X(_0786_)
  );
  sky130_fd_sc_hd__nand2_1 _0866_ (
    .A(_0826_),
    .B(_0842_),
    .Y(_0787_)
  );
  sky130_fd_sc_hd__a21oi_1 _0867_ (
    .A1(_0843_),
    .A2(_0825_),
    .B1(_0824_),
    .Y(_0788_)
  );
  sky130_fd_sc_hd__nor2_1 _0868_ (
    .A(_0786_),
    .B(_0788_),
    .Y(_0789_)
  );
  sky130_fd_sc_hd__o21bai_1 _0869_ (
    .A1(_0787_),
    .A2(_0788_),
    .B1_N(_0786_),
    .Y(_0790_)
  );
  sky130_fd_sc_hd__nand3_1 _0870_ (
    .A(_0843_),
    .B(_0826_),
    .C(_0825_),
    .Y(_0791_)
  );
  sky130_fd_sc_hd__a21o_1 _0871_ (
    .A1(_0843_),
    .A2(_0826_),
    .B1(_0825_),
    .X(_0792_)
  );
  sky130_fd_sc_hd__nand2_1 _0872_ (
    .A(_0791_),
    .B(_0792_),
    .Y(_0793_)
  );
  sky130_fd_sc_hd__nand2_1 _0873_ (
    .A(_0827_),
    .B(_0842_),
    .Y(_0794_)
  );
  sky130_fd_sc_hd__xnor2_1 _0874_ (
    .A(_0793_),
    .B(_0794_),
    .Y(_0795_)
  );
  sky130_fd_sc_hd__clkinv_1 _0875_ (
    .A(_0795_),
    .Y(_0796_)
  );
  sky130_fd_sc_hd__xnor2_1 _0876_ (
    .A(_0790_),
    .B(_0795_),
    .Y(_0797_)
  );
  sky130_fd_sc_hd__maj3_1 _0877_ (
    .A(_0841_),
    .B(_0790_),
    .C(_0796_),
    .X(_0798_)
  );
  sky130_fd_sc_hd__o21a_1 _0878_ (
    .A1(_0793_),
    .A2(_0794_),
    .B1(_0791_),
    .X(_0489_)
  );
  sky130_fd_sc_hd__nand3_1 _0879_ (
    .A(_0843_),
    .B(_0827_),
    .C(_0826_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__a21o_1 _0880_ (
    .A1(_0843_),
    .A2(_0827_),
    .B1(_0826_),
    .X(_0491_)
  );
  sky130_fd_sc_hd__nand3_1 _0881_ (
    .A(_0842_),
    .B(_0490_),
    .C(_0491_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__a21o_1 _0882_ (
    .A1(_0490_),
    .A2(_0491_),
    .B1(_0842_),
    .X(_0493_)
  );
  sky130_fd_sc_hd__nand2_1 _0883_ (
    .A(_0492_),
    .B(_0493_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__nor2_1 _0884_ (
    .A(_0489_),
    .B(_0494_),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__xor2_1 _0885_ (
    .A(_0489_),
    .B(_0494_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__and2_0 _0886_ (
    .A(_0798_),
    .B(_0496_),
    .X(_0497_)
  );
  sky130_fd_sc_hd__xnor2_1 _0887_ (
    .A(_0798_),
    .B(_0496_),
    .Y(_0498_)
  );
  sky130_fd_sc_hd__and3_1 _0888_ (
    .A(_0843_),
    .B(_0824_),
    .C(_0823_),
    .X(_0499_)
  );
  sky130_fd_sc_hd__nand2_1 _0889_ (
    .A(_0842_),
    .B(_0825_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__a21oi_1 _0890_ (
    .A1(_0843_),
    .A2(_0824_),
    .B1(_0823_),
    .Y(_0501_)
  );
  sky130_fd_sc_hd__nor2_1 _0891_ (
    .A(_0499_),
    .B(_0501_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__a31oi_1 _0892_ (
    .A1(_0842_),
    .A2(_0825_),
    .A3(_0502_),
    .B1(_0499_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__xor2_1 _0893_ (
    .A(_0787_),
    .B(_0789_),
    .X(_0504_)
  );
  sky130_fd_sc_hd__xor2_1 _0894_ (
    .A(_0503_),
    .B(_0504_),
    .X(_0505_)
  );
  sky130_fd_sc_hd__a21o_1 _0895_ (
    .A1(_0827_),
    .A2(_0841_),
    .B1(_0840_),
    .X(_0506_)
  );
  sky130_fd_sc_hd__nand3_1 _0896_ (
    .A(_0827_),
    .B(_0841_),
    .C(_0840_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__nand2_1 _0897_ (
    .A(_0506_),
    .B(_0507_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__maj3_1 _0898_ (
    .A(_0503_),
    .B(_0504_),
    .C(_0508_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__xnor2_1 _0899_ (
    .A(_0841_),
    .B(_0797_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__xnor2_1 _0900_ (
    .A(_0509_),
    .B(_0510_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__maj3_1 _0901_ (
    .A(_0507_),
    .B(_0509_),
    .C(_0510_),
    .X(_0512_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0902_ (
    .A(_0498_),
    .SLEEP(_0512_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__xnor2_1 _0903_ (
    .A(_0843_),
    .B(_0827_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__nor2_1 _0904_ (
    .A(_0787_),
    .B(_0514_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a311o_1 _0905_ (
    .A1(_0490_),
    .A2(_0492_),
    .A3(_0514_),
    .B1(_0515_),
    .C1(_0495_),
    .X(_0516_)
  );
  sky130_fd_sc_hd__nor2_1 _0906_ (
    .A(_0513_),
    .B(_0516_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__nand2_1 _0907_ (
    .A(_0498_),
    .B(_0512_),
    .Y(_0518_)
  );
  sky130_fd_sc_hd__nand2_1 _0908_ (
    .A(_0513_),
    .B(_0518_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__nand2_1 _0909_ (
    .A(_0843_),
    .B(_0822_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__and3_1 _0910_ (
    .A(_0843_),
    .B(_0823_),
    .C(_0822_),
    .X(_0521_)
  );
  sky130_fd_sc_hd__nand2_1 _0911_ (
    .A(_0842_),
    .B(_0824_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__a21oi_1 _0912_ (
    .A1(_0843_),
    .A2(_0823_),
    .B1(_0822_),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__nor3_1 _0913_ (
    .A(_0521_),
    .B(_0522_),
    .C(_0523_),
    .Y(_0524_)
  );
  sky130_fd_sc_hd__nor2_1 _0914_ (
    .A(_0521_),
    .B(_0524_),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__xor2_1 _0915_ (
    .A(_0500_),
    .B(_0502_),
    .X(_0526_)
  );
  sky130_fd_sc_hd__nor2_1 _0916_ (
    .A(_0525_),
    .B(_0526_),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__xnor2_1 _0917_ (
    .A(_0525_),
    .B(_0526_),
    .Y(_0528_)
  );
  sky130_fd_sc_hd__a22o_1 _0918_ (
    .A1(_0826_),
    .A2(_0841_),
    .B1(_0840_),
    .B2(_0827_),
    .X(_0529_)
  );
  sky130_fd_sc_hd__nand2_1 _0919_ (
    .A(_0826_),
    .B(_0840_),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__nand4_1 _0920_ (
    .A(_0827_),
    .B(_0826_),
    .C(_0841_),
    .D(_0840_),
    .Y(_0531_)
  );
  sky130_fd_sc_hd__nand3_1 _0921_ (
    .A(_0839_),
    .B(_0529_),
    .C(_0531_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__a21o_1 _0922_ (
    .A1(_0529_),
    .A2(_0531_),
    .B1(_0839_),
    .X(_0533_)
  );
  sky130_fd_sc_hd__nand2_1 _0923_ (
    .A(_0532_),
    .B(_0533_),
    .Y(_0534_)
  );
  sky130_fd_sc_hd__nor2_1 _0924_ (
    .A(_0528_),
    .B(_0534_),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__nor2_1 _0925_ (
    .A(_0527_),
    .B(_0535_),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__xnor2_1 _0926_ (
    .A(_0505_),
    .B(_0508_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__o21ai_0 _0927_ (
    .A1(_0527_),
    .A2(_0535_),
    .B1(_0537_),
    .Y(_0538_)
  );
  sky130_fd_sc_hd__xnor2_1 _0928_ (
    .A(_0536_),
    .B(_0537_),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__nand2_1 _0929_ (
    .A(_0531_),
    .B(_0532_),
    .Y(_0540_)
  );
  sky130_fd_sc_hd__nand2_1 _0930_ (
    .A(_0539_),
    .B(_0540_),
    .Y(_0541_)
  );
  sky130_fd_sc_hd__xnor2_1 _0931_ (
    .A(_0507_),
    .B(_0511_),
    .Y(_0542_)
  );
  sky130_fd_sc_hd__a21oi_1 _0932_ (
    .A1(_0538_),
    .A2(_0541_),
    .B1(_0542_),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__nand3_1 _0933_ (
    .A(_0513_),
    .B(_0518_),
    .C(_0543_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__xnor2_1 _0934_ (
    .A(_0519_),
    .B(_0543_),
    .Y(_0545_)
  );
  sky130_fd_sc_hd__clkinv_1 _0935_ (
    .A(_0545_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__nand2_1 _0936_ (
    .A(_0842_),
    .B(_0823_),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__maj3_1 _0937_ (
    .A(_0784_),
    .B(_0520_),
    .C(_0547_),
    .X(_0548_)
  );
  sky130_fd_sc_hd__o21ai_0 _0938_ (
    .A1(_0521_),
    .A2(_0523_),
    .B1(_0522_),
    .Y(_0549_)
  );
  sky130_fd_sc_hd__nand2b_1 _0939_ (
    .A_N(_0524_),
    .B(_0549_),
    .Y(_0550_)
  );
  sky130_fd_sc_hd__nand2_1 _0940_ (
    .A(_0827_),
    .B(_0839_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__nand2_1 _0941_ (
    .A(_0825_),
    .B(_0841_),
    .Y(_0552_)
  );
  sky130_fd_sc_hd__nand2_1 _0942_ (
    .A(_0825_),
    .B(_0840_),
    .Y(_0553_)
  );
  sky130_fd_sc_hd__xnor2_1 _0943_ (
    .A(_0530_),
    .B(_0552_),
    .Y(_0554_)
  );
  sky130_fd_sc_hd__xnor2_1 _0944_ (
    .A(_0551_),
    .B(_0554_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__maj3_1 _0945_ (
    .A(_0548_),
    .B(_0550_),
    .C(_0555_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__xnor2_1 _0946_ (
    .A(_0528_),
    .B(_0534_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__maj3_1 _0947_ (
    .A(_0530_),
    .B(_0551_),
    .C(_0552_),
    .X(_0558_)
  );
  sky130_fd_sc_hd__xnor2_1 _0948_ (
    .A(_0556_),
    .B(_0557_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__maj3_1 _0949_ (
    .A(_0556_),
    .B(_0557_),
    .C(_0558_),
    .X(_0560_)
  );
  sky130_fd_sc_hd__xor2_1 _0950_ (
    .A(_0539_),
    .B(_0540_),
    .X(_0561_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0951_ (
    .A(_0561_),
    .SLEEP(_0560_),
    .X(_0562_)
  );
  sky130_fd_sc_hd__and3_1 _0952_ (
    .A(_0538_),
    .B(_0541_),
    .C(_0542_),
    .X(_0563_)
  );
  sky130_fd_sc_hd__nor2_1 _0953_ (
    .A(_0543_),
    .B(_0563_),
    .Y(_0564_)
  );
  sky130_fd_sc_hd__and2_0 _0954_ (
    .A(_0562_),
    .B(_0564_),
    .X(_0565_)
  );
  sky130_fd_sc_hd__nor2_1 _0955_ (
    .A(_0562_),
    .B(_0564_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__xnor3_1 _0956_ (
    .A(_0815_),
    .B(_0520_),
    .C(_0547_),
    .X(_0567_)
  );
  sky130_fd_sc_hd__clkinv_1 _0957_ (
    .A(_0567_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__nand2_1 _0958_ (
    .A(_0842_),
    .B(_0815_),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__nor2_1 _0959_ (
    .A(_0520_),
    .B(_0569_),
    .Y(_0570_)
  );
  sky130_fd_sc_hd__nand4_1 _0960_ (
    .A(_0843_),
    .B(_0842_),
    .C(_0822_),
    .D(_0815_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__xnor2_1 _0961_ (
    .A(_0567_),
    .B(_0571_),
    .Y(_0572_)
  );
  sky130_fd_sc_hd__nand2_1 _0962_ (
    .A(_0826_),
    .B(_0839_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__nand2_1 _0963_ (
    .A(_0824_),
    .B(_0841_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__nand2_1 _0964_ (
    .A(_0824_),
    .B(_0840_),
    .Y(_0575_)
  );
  sky130_fd_sc_hd__xor2_1 _0965_ (
    .A(_0553_),
    .B(_0574_),
    .X(_0576_)
  );
  sky130_fd_sc_hd__xnor2_1 _0966_ (
    .A(_0573_),
    .B(_0576_),
    .Y(_0577_)
  );
  sky130_fd_sc_hd__maj3_1 _0967_ (
    .A(_0568_),
    .B(_0570_),
    .C(_0577_),
    .X(_0578_)
  );
  sky130_fd_sc_hd__xnor3_1 _0968_ (
    .A(_0548_),
    .B(_0550_),
    .C(_0555_),
    .X(_0579_)
  );
  sky130_fd_sc_hd__xnor2_1 _0969_ (
    .A(_0578_),
    .B(_0579_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__maj3_1 _0970_ (
    .A(_0553_),
    .B(_0573_),
    .C(_0574_),
    .X(_0581_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0971_ (
    .A(_0838_),
    .SLEEP(_0581_),
    .X(_0582_)
  );
  sky130_fd_sc_hd__xnor2_1 _0972_ (
    .A(_0838_),
    .B(_0581_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__maj3_1 _0973_ (
    .A(_0578_),
    .B(_0579_),
    .C(_0583_),
    .X(_0584_)
  );
  sky130_fd_sc_hd__xor2_1 _0974_ (
    .A(_0558_),
    .B(_0559_),
    .X(_0585_)
  );
  sky130_fd_sc_hd__xnor2_1 _0975_ (
    .A(_0584_),
    .B(_0585_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__maj3_1 _0976_ (
    .A(_0582_),
    .B(_0584_),
    .C(_0585_),
    .X(_0587_)
  );
  sky130_fd_sc_hd__xor2_1 _0977_ (
    .A(_0560_),
    .B(_0561_),
    .X(_0588_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0978_ (
    .A(_0587_),
    .SLEEP(_0588_),
    .X(_0589_)
  );
  sky130_fd_sc_hd__xnor2_1 _0979_ (
    .A(_0587_),
    .B(_0588_),
    .Y(_0590_)
  );
  sky130_fd_sc_hd__xnor2_1 _0980_ (
    .A(_0572_),
    .B(_0577_),
    .Y(_0591_)
  );
  sky130_fd_sc_hd__a22oi_1 _0981_ (
    .A1(_0842_),
    .A2(_0822_),
    .B1(_0815_),
    .B2(_0843_),
    .Y(_0592_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0982_ (
    .A(_0571_),
    .SLEEP(_0592_),
    .X(_0593_)
  );
  sky130_fd_sc_hd__nand2_1 _0983_ (
    .A(_0825_),
    .B(_0839_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__nand2_1 _0984_ (
    .A(_0841_),
    .B(_0823_),
    .Y(_0595_)
  );
  sky130_fd_sc_hd__nand2_1 _0985_ (
    .A(_0823_),
    .B(_0840_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__xor2_1 _0986_ (
    .A(_0575_),
    .B(_0595_),
    .X(_0597_)
  );
  sky130_fd_sc_hd__xnor2_1 _0987_ (
    .A(_0594_),
    .B(_0597_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__and2_0 _0988_ (
    .A(_0593_),
    .B(_0598_),
    .X(_0599_)
  );
  sky130_fd_sc_hd__xnor2_1 _0989_ (
    .A(_0591_),
    .B(_0599_),
    .Y(_0600_)
  );
  sky130_fd_sc_hd__nand2_1 _0990_ (
    .A(_0827_),
    .B(_0838_),
    .Y(_0601_)
  );
  sky130_fd_sc_hd__maj3_1 _0991_ (
    .A(_0575_),
    .B(_0594_),
    .C(_0595_),
    .X(_0602_)
  );
  sky130_fd_sc_hd__xor2_1 _0992_ (
    .A(_0601_),
    .B(_0602_),
    .X(_0603_)
  );
  sky130_fd_sc_hd__xnor2_1 _0993_ (
    .A(_0785_),
    .B(_0603_),
    .Y(_0604_)
  );
  sky130_fd_sc_hd__maj3_1 _0994_ (
    .A(_0591_),
    .B(_0599_),
    .C(_0604_),
    .X(_0605_)
  );
  sky130_fd_sc_hd__xnor2_1 _0995_ (
    .A(_0580_),
    .B(_0583_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__nand2_1 _0996_ (
    .A(_0605_),
    .B(_0606_),
    .Y(_0607_)
  );
  sky130_fd_sc_hd__maj3_1 _0997_ (
    .A(_0785_),
    .B(_0601_),
    .C(_0602_),
    .X(_0608_)
  );
  sky130_fd_sc_hd__xnor2_1 _0998_ (
    .A(_0605_),
    .B(_0606_),
    .Y(_0609_)
  );
  sky130_fd_sc_hd__o21ai_0 _0999_ (
    .A1(_0608_),
    .A2(_0609_),
    .B1(_0607_),
    .Y(_0610_)
  );
  sky130_fd_sc_hd__xnor2_1 _1000_ (
    .A(_0582_),
    .B(_0586_),
    .Y(_0611_)
  );
  sky130_fd_sc_hd__nand2_1 _1001_ (
    .A(_0610_),
    .B(_0611_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__xor3_1 _1002_ (
    .A(_0593_),
    .B(_0594_),
    .C(_0597_),
    .X(_0613_)
  );
  sky130_fd_sc_hd__nand2_1 _1003_ (
    .A(_0824_),
    .B(_0839_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__nand2_1 _1004_ (
    .A(_0841_),
    .B(_0822_),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__nand2_1 _1005_ (
    .A(_0840_),
    .B(_0822_),
    .Y(_0616_)
  );
  sky130_fd_sc_hd__xnor3_1 _1006_ (
    .A(_0596_),
    .B(_0614_),
    .C(_0615_),
    .X(_0617_)
  );
  sky130_fd_sc_hd__nor2b_1 _1007_ (
    .A(_0569_),
    .B_N(_0617_),
    .Y(_0618_)
  );
  sky130_fd_sc_hd__clkinv_1 _1008_ (
    .A(_0618_),
    .Y(_0619_)
  );
  sky130_fd_sc_hd__xor2_1 _1009_ (
    .A(_0613_),
    .B(_0618_),
    .X(_0620_)
  );
  sky130_fd_sc_hd__nand2_1 _1010_ (
    .A(_0827_),
    .B(_0831_),
    .Y(_0621_)
  );
  sky130_fd_sc_hd__nand2_1 _1011_ (
    .A(_0826_),
    .B(_0838_),
    .Y(_0622_)
  );
  sky130_fd_sc_hd__maj3_1 _1012_ (
    .A(_0596_),
    .B(_0614_),
    .C(_0615_),
    .X(_0623_)
  );
  sky130_fd_sc_hd__xnor2_1 _1013_ (
    .A(_0622_),
    .B(_0623_),
    .Y(_0624_)
  );
  sky130_fd_sc_hd__xnor2_1 _1014_ (
    .A(_0621_),
    .B(_0624_),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__maj3_1 _1015_ (
    .A(_0613_),
    .B(_0619_),
    .C(_0625_),
    .X(_0626_)
  );
  sky130_fd_sc_hd__xor2_1 _1016_ (
    .A(_0600_),
    .B(_0604_),
    .X(_0627_)
  );
  sky130_fd_sc_hd__maj3_1 _1017_ (
    .A(_0621_),
    .B(_0622_),
    .C(_0623_),
    .X(_0628_)
  );
  sky130_fd_sc_hd__xnor2_1 _1018_ (
    .A(_0626_),
    .B(_0627_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__maj3_1 _1019_ (
    .A(_0626_),
    .B(_0627_),
    .C(_0628_),
    .X(_0630_)
  );
  sky130_fd_sc_hd__xor2_1 _1020_ (
    .A(_0608_),
    .B(_0609_),
    .X(_0631_)
  );
  sky130_fd_sc_hd__clkinv_1 _1021_ (
    .A(_0631_),
    .Y(_0632_)
  );
  sky130_fd_sc_hd__xnor2_1 _1022_ (
    .A(_0630_),
    .B(_0631_),
    .Y(_0633_)
  );
  sky130_fd_sc_hd__xnor2_1 _1023_ (
    .A(_0620_),
    .B(_0625_),
    .Y(_0634_)
  );
  sky130_fd_sc_hd__xnor2_1 _1024_ (
    .A(_0569_),
    .B(_0617_),
    .Y(_0635_)
  );
  sky130_fd_sc_hd__nand2_1 _1025_ (
    .A(_0826_),
    .B(_0831_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__nand2_1 _1026_ (
    .A(_0825_),
    .B(_0838_),
    .Y(_0637_)
  );
  sky130_fd_sc_hd__nand2_1 _1027_ (
    .A(_0841_),
    .B(_0815_),
    .Y(_0638_)
  );
  sky130_fd_sc_hd__nand2_1 _1028_ (
    .A(_0823_),
    .B(_0839_),
    .Y(_0639_)
  );
  sky130_fd_sc_hd__maj3_1 _1029_ (
    .A(_0616_),
    .B(_0638_),
    .C(_0639_),
    .X(_0640_)
  );
  sky130_fd_sc_hd__xnor3_1 _1030_ (
    .A(_0636_),
    .B(_0637_),
    .C(_0640_),
    .X(_0641_)
  );
  sky130_fd_sc_hd__nand2_1 _1031_ (
    .A(_0635_),
    .B(_0641_),
    .Y(_0642_)
  );
  sky130_fd_sc_hd__maj3_1 _1032_ (
    .A(_0636_),
    .B(_0637_),
    .C(_0640_),
    .X(_0643_)
  );
  sky130_fd_sc_hd__maj3_1 _1033_ (
    .A(_0634_),
    .B(_0642_),
    .C(_0643_),
    .X(_0644_)
  );
  sky130_fd_sc_hd__xnor2_1 _1034_ (
    .A(_0628_),
    .B(_0629_),
    .Y(_0645_)
  );
  sky130_fd_sc_hd__xor2_1 _1035_ (
    .A(_0644_),
    .B(_0645_),
    .X(_0646_)
  );
  sky130_fd_sc_hd__xnor2_1 _1036_ (
    .A(_0635_),
    .B(_0641_),
    .Y(_0647_)
  );
  sky130_fd_sc_hd__xor3_1 _1037_ (
    .A(_0616_),
    .B(_0638_),
    .C(_0639_),
    .X(_0648_)
  );
  sky130_fd_sc_hd__nand2_1 _1038_ (
    .A(_0825_),
    .B(_0831_),
    .Y(_0649_)
  );
  sky130_fd_sc_hd__and2_0 _1039_ (
    .A(_0824_),
    .B(_0838_),
    .X(_0650_)
  );
  sky130_fd_sc_hd__and4_1 _1040_ (
    .A(_0840_),
    .B(_0822_),
    .C(_0839_),
    .D(_0815_),
    .X(_0651_)
  );
  sky130_fd_sc_hd__nand2_1 _1041_ (
    .A(_0650_),
    .B(_0651_),
    .Y(_0652_)
  );
  sky130_fd_sc_hd__nor2_1 _1042_ (
    .A(_0650_),
    .B(_0651_),
    .Y(_0653_)
  );
  sky130_fd_sc_hd__xnor3_1 _1043_ (
    .A(_0649_),
    .B(_0650_),
    .C(_0651_),
    .X(_0654_)
  );
  sky130_fd_sc_hd__nand2b_1 _1044_ (
    .A_N(_0648_),
    .B(_0654_),
    .Y(_0655_)
  );
  sky130_fd_sc_hd__o21a_1 _1045_ (
    .A1(_0649_),
    .A2(_0653_),
    .B1(_0652_),
    .X(_0656_)
  );
  sky130_fd_sc_hd__xnor2_1 _1046_ (
    .A(_0647_),
    .B(_0655_),
    .Y(_0657_)
  );
  sky130_fd_sc_hd__maj3_1 _1047_ (
    .A(_0647_),
    .B(_0655_),
    .C(_0656_),
    .X(_0658_)
  );
  sky130_fd_sc_hd__xnor3_1 _1048_ (
    .A(_0634_),
    .B(_0642_),
    .C(_0643_),
    .X(_0659_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1049_ (
    .A(_0659_),
    .SLEEP(_0658_),
    .X(_0660_)
  );
  sky130_fd_sc_hd__xnor2_1 _1050_ (
    .A(_0658_),
    .B(_0659_),
    .Y(_0661_)
  );
  sky130_fd_sc_hd__xnor2_1 _1051_ (
    .A(_0648_),
    .B(_0654_),
    .Y(_0662_)
  );
  sky130_fd_sc_hd__a22oi_1 _1052_ (
    .A1(_0822_),
    .A2(_0839_),
    .B1(_0815_),
    .B2(_0840_),
    .Y(_0663_)
  );
  sky130_fd_sc_hd__and4_1 _1053_ (
    .A(_0824_),
    .B(_0823_),
    .C(_0838_),
    .D(_0831_),
    .X(_0664_)
  );
  sky130_fd_sc_hd__a22oi_1 _1054_ (
    .A1(_0823_),
    .A2(_0838_),
    .B1(_0831_),
    .B2(_0824_),
    .Y(_0665_)
  );
  sky130_fd_sc_hd__nor4_1 _1055_ (
    .A(_0651_),
    .B(_0663_),
    .C(_0664_),
    .D(_0665_),
    .Y(_0666_)
  );
  sky130_fd_sc_hd__xnor3_1 _1056_ (
    .A(_0648_),
    .B(_0654_),
    .C(_0666_),
    .X(_0667_)
  );
  sky130_fd_sc_hd__o21a_1 _1057_ (
    .A1(_0664_),
    .A2(_0666_),
    .B1(_0662_),
    .X(_0668_)
  );
  sky130_fd_sc_hd__xor2_1 _1058_ (
    .A(_0656_),
    .B(_0657_),
    .X(_0669_)
  );
  sky130_fd_sc_hd__xor2_1 _1059_ (
    .A(_0668_),
    .B(_0669_),
    .X(_0670_)
  );
  sky130_fd_sc_hd__xnor2_1 _1060_ (
    .A(_0664_),
    .B(_0667_),
    .Y(_0671_)
  );
  sky130_fd_sc_hd__o22ai_1 _1061_ (
    .A1(_0651_),
    .A2(_0663_),
    .B1(_0664_),
    .B2(_0665_),
    .Y(_0672_)
  );
  sky130_fd_sc_hd__nand2b_1 _1062_ (
    .A_N(_0666_),
    .B(_0672_),
    .Y(_0673_)
  );
  sky130_fd_sc_hd__nand4_1 _1063_ (
    .A(_0823_),
    .B(_0822_),
    .C(_0838_),
    .D(_0831_),
    .Y(_0674_)
  );
  sky130_fd_sc_hd__a22o_1 _1064_ (
    .A1(_0822_),
    .A2(_0838_),
    .B1(_0831_),
    .B2(_0823_),
    .X(_0675_)
  );
  sky130_fd_sc_hd__nand4_1 _1065_ (
    .A(_0839_),
    .B(_0815_),
    .C(_0674_),
    .D(_0675_),
    .Y(_0676_)
  );
  sky130_fd_sc_hd__a21oi_1 _1066_ (
    .A1(_0674_),
    .A2(_0676_),
    .B1(_0673_),
    .Y(_0677_)
  );
  sky130_fd_sc_hd__nand2b_1 _1067_ (
    .A_N(_0671_),
    .B(_0677_),
    .Y(_0678_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1068_ (
    .A(_0671_),
    .SLEEP(_0677_),
    .X(_0679_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1069_ (
    .A(_0678_),
    .SLEEP(_0679_),
    .X(_0680_)
  );
  sky130_fd_sc_hd__nand2_1 _1070_ (
    .A(_0673_),
    .B(_0674_),
    .Y(_0681_)
  );
  sky130_fd_sc_hd__a22oi_1 _1071_ (
    .A1(_0839_),
    .A2(_0815_),
    .B1(_0674_),
    .B2(_0675_),
    .Y(_0682_)
  );
  sky130_fd_sc_hd__nand3_1 _1072_ (
    .A(_0822_),
    .B(_0815_),
    .C(_0838_),
    .Y(_0683_)
  );
  sky130_fd_sc_hd__nor4b_1 _1073_ (
    .A(_0785_),
    .B(_0683_),
    .C(_0682_),
    .D_N(_0676_),
    .Y(_0684_)
  );
  sky130_fd_sc_hd__o211ai_1 _1074_ (
    .A1(_0673_),
    .A2(_0674_),
    .B1(_0681_),
    .C1(_0684_),
    .Y(_0685_)
  );
  sky130_fd_sc_hd__o21ai_0 _1075_ (
    .A1(_0679_),
    .A2(_0685_),
    .B1(_0678_),
    .Y(_0686_)
  );
  sky130_fd_sc_hd__maj3_1 _1076_ (
    .A(_0668_),
    .B(_0669_),
    .C(_0686_),
    .X(_0687_)
  );
  sky130_fd_sc_hd__a21oi_1 _1077_ (
    .A1(_0661_),
    .A2(_0687_),
    .B1(_0660_),
    .Y(_0688_)
  );
  sky130_fd_sc_hd__maj3_1 _1078_ (
    .A(_0644_),
    .B(_0645_),
    .C(_0688_),
    .X(_0689_)
  );
  sky130_fd_sc_hd__maj3_1 _1079_ (
    .A(_0630_),
    .B(_0632_),
    .C(_0689_),
    .X(_0690_)
  );
  sky130_fd_sc_hd__xnor2_1 _1080_ (
    .A(_0610_),
    .B(_0611_),
    .Y(_0691_)
  );
  sky130_fd_sc_hd__o21ai_0 _1081_ (
    .A1(_0690_),
    .A2(_0691_),
    .B1(_0612_),
    .Y(_0692_)
  );
  sky130_fd_sc_hd__a21oi_1 _1082_ (
    .A1(_0590_),
    .A2(_0692_),
    .B1(_0589_),
    .Y(_0693_)
  );
  sky130_fd_sc_hd__a211oi_1 _1083_ (
    .A1(_0590_),
    .A2(_0692_),
    .B1(_0565_),
    .C1(_0589_),
    .Y(_0694_)
  );
  sky130_fd_sc_hd__nor2_1 _1084_ (
    .A(_0566_),
    .B(_0694_),
    .Y(_0695_)
  );
  sky130_fd_sc_hd__o31ai_1 _1085_ (
    .A1(_0546_),
    .A2(_0566_),
    .A3(_0694_),
    .B1(_0544_),
    .Y(_0696_)
  );
  sky130_fd_sc_hd__nand2b_1 _1086_ (
    .A_N(_0497_),
    .B(_0513_),
    .Y(_0697_)
  );
  sky130_fd_sc_hd__xnor2_1 _1087_ (
    .A(_0516_),
    .B(_0697_),
    .Y(_0698_)
  );
  sky130_fd_sc_hd__a21oi_1 _1088_ (
    .A1(_0696_),
    .A2(_0698_),
    .B1(_0517_),
    .Y(_0699_)
  );
  sky130_fd_sc_hd__a21o_1 _1089_ (
    .A1(_0843_),
    .A2(_0827_),
    .B1(_0515_),
    .X(_0700_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1090_ (
    .A(_0497_),
    .SLEEP(_0516_),
    .X(_0701_)
  );
  sky130_fd_sc_hd__nor3_1 _1091_ (
    .A(_0495_),
    .B(_0700_),
    .C(_0701_),
    .Y(_0702_)
  );
  sky130_fd_sc_hd__nand2_1 _1092_ (
    .A(_0699_),
    .B(_0702_),
    .Y(_0703_)
  );
  sky130_fd_sc_hd__clkinv_1 _1093_ (
    .A(_0703_),
    .Y(_0704_)
  );
  sky130_fd_sc_hd__nor2_1 _1094_ (
    .A(_0844_),
    .B(_0828_),
    .Y(_0705_)
  );
  sky130_fd_sc_hd__xnor2_1 _1095_ (
    .A(_0844_),
    .B(_0828_),
    .Y(_0706_)
  );
  sky130_fd_sc_hd__xor2_1 _1096_ (
    .A(_0703_),
    .B(_0706_),
    .X(_0470_)
  );
  sky130_fd_sc_hd__nand2_1 _1097_ (
    .A(_0845_),
    .B(_0829_),
    .Y(_0707_)
  );
  sky130_fd_sc_hd__xnor2_1 _1098_ (
    .A(_0845_),
    .B(_0829_),
    .Y(_0708_)
  );
  sky130_fd_sc_hd__nor2_1 _1099_ (
    .A(_0705_),
    .B(_0708_),
    .Y(_0709_)
  );
  sky130_fd_sc_hd__xor2_1 _1100_ (
    .A(_0705_),
    .B(_0708_),
    .X(_0710_)
  );
  sky130_fd_sc_hd__a21oi_1 _1101_ (
    .A1(_0703_),
    .A2(_0706_),
    .B1(_0710_),
    .Y(_0711_)
  );
  sky130_fd_sc_hd__nand2_1 _1102_ (
    .A(_0706_),
    .B(_0710_),
    .Y(_0712_)
  );
  sky130_fd_sc_hd__nand3_1 _1103_ (
    .A(_0703_),
    .B(_0706_),
    .C(_0710_),
    .Y(_0713_)
  );
  sky130_fd_sc_hd__nor2b_1 _1104_ (
    .A(_0711_),
    .B_N(_0713_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__xnor2_1 _1105_ (
    .A(_0846_),
    .B(_0830_),
    .Y(_0714_)
  );
  sky130_fd_sc_hd__nor2_1 _1106_ (
    .A(_0707_),
    .B(_0714_),
    .Y(_0715_)
  );
  sky130_fd_sc_hd__xor2_1 _1107_ (
    .A(_0707_),
    .B(_0714_),
    .X(_0716_)
  );
  sky130_fd_sc_hd__xnor2_1 _1108_ (
    .A(_0709_),
    .B(_0716_),
    .Y(_0717_)
  );
  sky130_fd_sc_hd__a211oi_1 _1109_ (
    .A1(_0699_),
    .A2(_0702_),
    .B1(_0712_),
    .C1(_0717_),
    .Y(_0718_)
  );
  sky130_fd_sc_hd__xor2_1 _1110_ (
    .A(_0713_),
    .B(_0717_),
    .X(_0472_)
  );
  sky130_fd_sc_hd__a21oi_1 _1111_ (
    .A1(_0709_),
    .A2(_0716_),
    .B1(_0715_),
    .Y(_0719_)
  );
  sky130_fd_sc_hd__nand2_1 _1112_ (
    .A(_0832_),
    .B(_0816_),
    .Y(_0720_)
  );
  sky130_fd_sc_hd__xor2_1 _1113_ (
    .A(_0832_),
    .B(_0816_),
    .X(_0721_)
  );
  sky130_fd_sc_hd__a21oi_1 _1114_ (
    .A1(_0846_),
    .A2(_0830_),
    .B1(_0721_),
    .Y(_0722_)
  );
  sky130_fd_sc_hd__nand3_1 _1115_ (
    .A(_0846_),
    .B(_0830_),
    .C(_0721_),
    .Y(_0723_)
  );
  sky130_fd_sc_hd__nor2b_1 _1116_ (
    .A(_0722_),
    .B_N(_0723_),
    .Y(_0724_)
  );
  sky130_fd_sc_hd__xnor2_1 _1117_ (
    .A(_0719_),
    .B(_0724_),
    .Y(_0725_)
  );
  sky130_fd_sc_hd__nor2_1 _1118_ (
    .A(_0718_),
    .B(_0725_),
    .Y(_0726_)
  );
  sky130_fd_sc_hd__nand2b_1 _1119_ (
    .A_N(_0717_),
    .B(_0725_),
    .Y(_0727_)
  );
  sky130_fd_sc_hd__a211oi_1 _1120_ (
    .A1(_0699_),
    .A2(_0702_),
    .B1(_0712_),
    .C1(_0727_),
    .Y(_0728_)
  );
  sky130_fd_sc_hd__nor2_1 _1121_ (
    .A(_0726_),
    .B(_0728_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__o21ai_0 _1122_ (
    .A1(_0719_),
    .A2(_0722_),
    .B1(_0723_),
    .Y(_0729_)
  );
  sky130_fd_sc_hd__nand2_1 _1123_ (
    .A(_0833_),
    .B(_0817_),
    .Y(_0730_)
  );
  sky130_fd_sc_hd__xnor2_1 _1124_ (
    .A(_0833_),
    .B(_0817_),
    .Y(_0731_)
  );
  sky130_fd_sc_hd__nor2_1 _1125_ (
    .A(_0720_),
    .B(_0731_),
    .Y(_0732_)
  );
  sky130_fd_sc_hd__xor2_1 _1126_ (
    .A(_0720_),
    .B(_0731_),
    .X(_0733_)
  );
  sky130_fd_sc_hd__and2_0 _1127_ (
    .A(_0729_),
    .B(_0733_),
    .X(_0734_)
  );
  sky130_fd_sc_hd__xnor2_1 _1128_ (
    .A(_0729_),
    .B(_0733_),
    .Y(_0735_)
  );
  sky130_fd_sc_hd__a2111oi_0 _1129_ (
    .A1(_0699_),
    .A2(_0702_),
    .B1(_0712_),
    .C1(_0727_),
    .D1(_0735_),
    .Y(_0736_)
  );
  sky130_fd_sc_hd__xnor2_1 _1130_ (
    .A(_0728_),
    .B(_0735_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__and2_0 _1131_ (
    .A(_0834_),
    .B(_0818_),
    .X(_0737_)
  );
  sky130_fd_sc_hd__nor2_1 _1132_ (
    .A(_0834_),
    .B(_0818_),
    .Y(_0738_)
  );
  sky130_fd_sc_hd__nor2_1 _1133_ (
    .A(_0737_),
    .B(_0738_),
    .Y(_0739_)
  );
  sky130_fd_sc_hd__xnor2_1 _1134_ (
    .A(_0730_),
    .B(_0739_),
    .Y(_0740_)
  );
  sky130_fd_sc_hd__o21ai_0 _1135_ (
    .A1(_0732_),
    .A2(_0734_),
    .B1(_0740_),
    .Y(_0741_)
  );
  sky130_fd_sc_hd__nor3_1 _1136_ (
    .A(_0732_),
    .B(_0734_),
    .C(_0740_),
    .Y(_0742_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1137_ (
    .A(_0741_),
    .SLEEP(_0742_),
    .X(_0743_)
  );
  sky130_fd_sc_hd__nand2_1 _1138_ (
    .A(_0736_),
    .B(_0743_),
    .Y(_0744_)
  );
  sky130_fd_sc_hd__xor2_1 _1139_ (
    .A(_0736_),
    .B(_0743_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__o31ai_1 _1140_ (
    .A1(_0730_),
    .A2(_0737_),
    .A3(_0738_),
    .B1(_0741_),
    .Y(_0745_)
  );
  sky130_fd_sc_hd__nand2_1 _1141_ (
    .A(_0835_),
    .B(_0819_),
    .Y(_0746_)
  );
  sky130_fd_sc_hd__xor2_1 _1142_ (
    .A(_0835_),
    .B(_0819_),
    .X(_0747_)
  );
  sky130_fd_sc_hd__xnor2_1 _1143_ (
    .A(_0737_),
    .B(_0747_),
    .Y(_0748_)
  );
  sky130_fd_sc_hd__xnor2_1 _1144_ (
    .A(_0745_),
    .B(_0748_),
    .Y(_0749_)
  );
  sky130_fd_sc_hd__nand3_1 _1145_ (
    .A(_0736_),
    .B(_0743_),
    .C(_0749_),
    .Y(_0750_)
  );
  sky130_fd_sc_hd__xnor2_1 _1146_ (
    .A(_0744_),
    .B(_0749_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__maj3_1 _1147_ (
    .A(_0737_),
    .B(_0745_),
    .C(_0747_),
    .X(_0751_)
  );
  sky130_fd_sc_hd__xor2_1 _1148_ (
    .A(_0836_),
    .B(_0820_),
    .X(_0752_)
  );
  sky130_fd_sc_hd__xnor2_1 _1149_ (
    .A(_0746_),
    .B(_0752_),
    .Y(_0753_)
  );
  sky130_fd_sc_hd__xnor2_1 _1150_ (
    .A(_0751_),
    .B(_0753_),
    .Y(_0754_)
  );
  sky130_fd_sc_hd__xnor2_1 _1151_ (
    .A(_0750_),
    .B(_0754_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__xnor2_1 _1152_ (
    .A(_0680_),
    .B(_0685_),
    .Y(_0755_)
  );
  sky130_fd_sc_hd__nor2_1 _1153_ (
    .A(_0703_),
    .B(_0755_),
    .Y(_0756_)
  );
  sky130_fd_sc_hd__xnor2_1 _1154_ (
    .A(_0670_),
    .B(_0686_),
    .Y(_0757_)
  );
  sky130_fd_sc_hd__a21oi_1 _1155_ (
    .A1(_0703_),
    .A2(_0757_),
    .B1(_0756_),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__xor2_1 _1156_ (
    .A(_0661_),
    .B(_0687_),
    .X(_0758_)
  );
  sky130_fd_sc_hd__nand2_1 _1157_ (
    .A(_0703_),
    .B(_0758_),
    .Y(_0759_)
  );
  sky130_fd_sc_hd__o21ai_0 _1158_ (
    .A1(_0703_),
    .A2(_0757_),
    .B1(_0759_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__xnor2_1 _1159_ (
    .A(_0646_),
    .B(_0688_),
    .Y(_0760_)
  );
  sky130_fd_sc_hd__mux2_1 _1160_ (
    .A0(_0758_),
    .A1(_0760_),
    .S(_0703_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__xnor2_1 _1161_ (
    .A(_0633_),
    .B(_0689_),
    .Y(_0761_)
  );
  sky130_fd_sc_hd__mux2_1 _1162_ (
    .A0(_0760_),
    .A1(_0761_),
    .S(_0703_),
    .X(_0482_)
  );
  sky130_fd_sc_hd__xor2_1 _1163_ (
    .A(_0690_),
    .B(_0691_),
    .X(_0762_)
  );
  sky130_fd_sc_hd__mux2_1 _1164_ (
    .A0(_0761_),
    .A1(_0762_),
    .S(_0703_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__xor2_1 _1165_ (
    .A(_0590_),
    .B(_0692_),
    .X(_0763_)
  );
  sky130_fd_sc_hd__mux2_1 _1166_ (
    .A0(_0762_),
    .A1(_0763_),
    .S(_0703_),
    .X(_0484_)
  );
  sky130_fd_sc_hd__nor2_1 _1167_ (
    .A(_0565_),
    .B(_0566_),
    .Y(_0764_)
  );
  sky130_fd_sc_hd__xor2_1 _1168_ (
    .A(_0693_),
    .B(_0764_),
    .X(_0765_)
  );
  sky130_fd_sc_hd__nor2_1 _1169_ (
    .A(_0703_),
    .B(_0763_),
    .Y(_0766_)
  );
  sky130_fd_sc_hd__a21oi_1 _1170_ (
    .A1(_0703_),
    .A2(_0765_),
    .B1(_0766_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__xnor2_1 _1171_ (
    .A(_0545_),
    .B(_0695_),
    .Y(_0767_)
  );
  sky130_fd_sc_hd__mux2i_1 _1172_ (
    .A0(_0765_),
    .A1(_0767_),
    .S(_0703_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__xor2_1 _1173_ (
    .A(_0696_),
    .B(_0698_),
    .X(_0768_)
  );
  sky130_fd_sc_hd__nand2_1 _1174_ (
    .A(_0703_),
    .B(_0768_),
    .Y(_0769_)
  );
  sky130_fd_sc_hd__o21ai_0 _1175_ (
    .A1(_0703_),
    .A2(_0767_),
    .B1(_0769_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__o21ai_0 _1176_ (
    .A1(_0495_),
    .A2(_0701_),
    .B1(_0700_),
    .Y(_0770_)
  );
  sky130_fd_sc_hd__a21oi_1 _1177_ (
    .A1(_0699_),
    .A2(_0770_),
    .B1(_0702_),
    .Y(_0771_)
  );
  sky130_fd_sc_hd__a21o_1 _1178_ (
    .A1(_0704_),
    .A2(_0768_),
    .B1(_0771_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__or4_1 _1179_ (
    .A(_0825_),
    .B(_0824_),
    .C(_0823_),
    .D(_0822_),
    .X(_0772_)
  );
  sky130_fd_sc_hd__or4_1 _1180_ (
    .A(_0821_),
    .B(_0828_),
    .C(_0827_),
    .D(_0826_),
    .X(_0773_)
  );
  sky130_fd_sc_hd__nor4_1 _1181_ (
    .A(_0817_),
    .B(_0818_),
    .C(_0819_),
    .D(_0820_),
    .Y(_0774_)
  );
  sky130_fd_sc_hd__nor3_1 _1182_ (
    .A(_0815_),
    .B(_0830_),
    .C(_0816_),
    .Y(_0775_)
  );
  sky130_fd_sc_hd__nor3_1 _1183_ (
    .A(_0829_),
    .B(_0772_),
    .C(_0773_),
    .Y(_0776_)
  );
  sky130_fd_sc_hd__nand3_1 _1184_ (
    .A(_0774_),
    .B(_0775_),
    .C(_0776_),
    .Y(_0777_)
  );
  sky130_fd_sc_hd__or4_1 _1185_ (
    .A(_0845_),
    .B(_0834_),
    .C(_0835_),
    .D(_0836_),
    .X(_0778_)
  );
  sky130_fd_sc_hd__nor3_1 _1186_ (
    .A(_0846_),
    .B(_0833_),
    .C(_0778_),
    .Y(_0779_)
  );
  sky130_fd_sc_hd__nor4_1 _1187_ (
    .A(_0837_),
    .B(_0844_),
    .C(_0831_),
    .D(_0832_),
    .Y(_0780_)
  );
  sky130_fd_sc_hd__or4_1 _1188_ (
    .A(_0843_),
    .B(_0842_),
    .C(_0841_),
    .D(_0838_),
    .X(_0781_)
  );
  sky130_fd_sc_hd__nor3_1 _1189_ (
    .A(_0840_),
    .B(_0839_),
    .C(_0781_),
    .Y(_0782_)
  );
  sky130_fd_sc_hd__nand3_1 _1190_ (
    .A(_0779_),
    .B(_0780_),
    .C(_0782_),
    .Y(_0783_)
  );
  sky130_fd_sc_hd__and3_1 _1191_ (
    .A(_0807_),
    .B(_0777_),
    .C(_0783_),
    .X(_0847_)
  );
  sky130_fd_sc_hd__and3_1 _1192_ (
    .A(_0808_),
    .B(_0777_),
    .C(_0783_),
    .X(_0853_)
  );
  sky130_fd_sc_hd__and3_1 _1193_ (
    .A(_0809_),
    .B(_0777_),
    .C(_0783_),
    .X(_0854_)
  );
  sky130_fd_sc_hd__and3_1 _1194_ (
    .A(_0810_),
    .B(_0777_),
    .C(_0783_),
    .X(_0855_)
  );
  sky130_fd_sc_hd__and3_1 _1195_ (
    .A(_0811_),
    .B(_0777_),
    .C(_0783_),
    .X(_0856_)
  );
  sky130_fd_sc_hd__and3_1 _1196_ (
    .A(_0812_),
    .B(_0777_),
    .C(_0783_),
    .X(_0857_)
  );
  sky130_fd_sc_hd__and3_1 _1197_ (
    .A(_0813_),
    .B(_0777_),
    .C(_0783_),
    .X(_0858_)
  );
  sky130_fd_sc_hd__and3_1 _1198_ (
    .A(_0799_),
    .B(_0777_),
    .C(_0783_),
    .X(_0859_)
  );
  sky130_fd_sc_hd__and3_1 _1199_ (
    .A(_0800_),
    .B(_0777_),
    .C(_0783_),
    .X(_0860_)
  );
  sky130_fd_sc_hd__and3_1 _1200_ (
    .A(_0801_),
    .B(_0777_),
    .C(_0783_),
    .X(_0861_)
  );
  sky130_fd_sc_hd__and3_1 _1201_ (
    .A(_0802_),
    .B(_0777_),
    .C(_0783_),
    .X(_0848_)
  );
  sky130_fd_sc_hd__and3_1 _1202_ (
    .A(_0803_),
    .B(_0777_),
    .C(_0783_),
    .X(_0849_)
  );
  sky130_fd_sc_hd__and3_1 _1203_ (
    .A(_0804_),
    .B(_0777_),
    .C(_0783_),
    .X(_0850_)
  );
  sky130_fd_sc_hd__and3_1 _1204_ (
    .A(_0805_),
    .B(_0777_),
    .C(_0783_),
    .X(_0851_)
  );
  sky130_fd_sc_hd__and3_1 _1205_ (
    .A(_0806_),
    .B(_0777_),
    .C(_0783_),
    .X(_0852_)
  );
  (* src = "src/fpmul.v:57.16-63.2" *)
  \$paramod\myreg\N=s32'00000000000000000000000000000001  reg1en (
    .clk(clk),
    .d(en),
    .en(1'h1),
    .q(end1),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/fpmul.v:43.9-48.6" *)
  rounder rounder0 (
    .exp_i(exp_grs),
    .exp_o(p_exp),
    .mant_i(mant_grs),
    .mant_o(p_mant)
  );
  assign ready = end1;
  assign result = { p_s, y[14:0] };
  assign y[15] = p_s;
  assign _0479_ = 1'h1;
  assign _0837_ = x2[15];
  assign _0821_ = x1[15];
  assign p_s = _0814_;
  assign _0844_ = x2[7];
  assign _0828_ = x1[7];
  assign _0843_ = x2[6];
  assign _0827_ = x1[6];
  assign _0826_ = x1[5];
  assign _0842_ = x2[5];
  assign _0825_ = x1[4];
  assign _0824_ = x1[3];
  assign _0841_ = x2[4];
  assign _0823_ = x1[2];
  assign _0840_ = x2[3];
  assign _0822_ = x1[1];
  assign _0839_ = x2[2];
  assign _0815_ = x1[0];
  assign _0838_ = x2[1];
  assign _0831_ = x2[0];
  assign exp_grs[0] = _0470_;
  assign _0845_ = x2[8];
  assign _0829_ = x1[8];
  assign exp_grs[1] = _0471_;
  assign _0846_ = x2[9];
  assign _0830_ = x1[9];
  assign exp_grs[2] = _0472_;
  assign _0832_ = x2[10];
  assign _0816_ = x1[10];
  assign exp_grs[3] = _0473_;
  assign _0833_ = x2[11];
  assign _0817_ = x1[11];
  assign exp_grs[4] = _0474_;
  assign _0834_ = x2[12];
  assign _0818_ = x1[12];
  assign exp_grs[5] = _0475_;
  assign _0835_ = x2[13];
  assign _0819_ = x1[13];
  assign exp_grs[6] = _0476_;
  assign _0836_ = x2[14];
  assign _0820_ = x1[14];
  assign exp_grs[7] = _0477_;
  assign mant_grs[0] = _0478_;
  assign mant_grs[1] = _0480_;
  assign mant_grs[2] = _0481_;
  assign mant_grs[3] = _0482_;
  assign mant_grs[4] = _0483_;
  assign mant_grs[5] = _0484_;
  assign mant_grs[6] = _0485_;
  assign mant_grs[7] = _0486_;
  assign mant_grs[8] = _0487_;
  assign mant_grs[9] = _0488_;
  assign mant_grs[10] = _0479_;
  assign _0807_ = p_mant[0];
  assign y[0] = _0847_;
  assign _0808_ = p_mant[1];
  assign y[1] = _0853_;
  assign _0809_ = p_mant[2];
  assign y[2] = _0854_;
  assign _0810_ = p_mant[3];
  assign y[3] = _0855_;
  assign _0811_ = p_mant[4];
  assign y[4] = _0856_;
  assign _0812_ = p_mant[5];
  assign y[5] = _0857_;
  assign _0813_ = p_mant[6];
  assign y[6] = _0858_;
  assign _0799_ = p_exp[0];
  assign y[7] = _0859_;
  assign _0800_ = p_exp[1];
  assign y[8] = _0860_;
  assign _0801_ = p_exp[2];
  assign y[9] = _0861_;
  assign _0802_ = p_exp[3];
  assign y[10] = _0848_;
  assign _0803_ = p_exp[4];
  assign y[11] = _0849_;
  assign _0804_ = p_exp[5];
  assign y[12] = _0850_;
  assign _0805_ = p_exp[6];
  assign y[13] = _0851_;
  assign _0806_ = p_exp[7];
  assign y[14] = _0852_;
endmodule

(* src = "src/rounder.v:1.1-56.10" *)
module rounder(mant_i, exp_i, mant_o, exp_o);
  (* src = "src/rounder.v:2.18-2.24" *)
  input [10:0] mant_i;
  wire [10:0] mant_i;
  (* src = "src/rounder.v:3.17-3.22" *)
  input [7:0] exp_i;
  wire [7:0] exp_i;
  (* src = "src/rounder.v:4.18-4.24" *)
  output [7:0] mant_o;
  wire [7:0] mant_o;
  (* src = "src/rounder.v:5.18-5.23" *)
  output [7:0] exp_o;
  wire [7:0] exp_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _094_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _095_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _096_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _097_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _098_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _099_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _100_;
  (* src = "src/rounder.v:3.17-3.22" *)
  wire _101_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _102_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _103_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _104_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _105_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _106_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _107_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _108_;
  (* src = "src/rounder.v:5.18-5.23" *)
  wire _109_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _110_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _111_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _112_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _113_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _114_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _115_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _116_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _117_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _118_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _119_;
  (* src = "src/rounder.v:2.18-2.24" *)
  wire _120_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _121_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _122_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _123_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _124_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _125_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _126_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _127_;
  (* src = "src/rounder.v:4.18-4.24" *)
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  (* src = "src/rounder.v:10.12-10.29" *)
  wire [7:0] mant_shift_output;
  sky130_fd_sc_hd__clkinv_1 _150_ (
    .A(_111_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(_120_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _152_ (
    .A(_114_),
    .B(_113_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o21ai_0 _153_ (
    .A1(_112_),
    .A2(_110_),
    .B1(_113_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__mux2i_1 _154_ (
    .A0(_132_),
    .A1(_113_),
    .S(_114_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(_115_),
    .B(_131_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a31oi_1 _156_ (
    .A1(_114_),
    .A2(_113_),
    .A3(_115_),
    .B1(_116_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__and4_1 _157_ (
    .A(_114_),
    .B(_113_),
    .C(_116_),
    .D(_115_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(_133_),
    .B(_134_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _159_ (
    .A(_117_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xor2_1 _160_ (
    .A(_117_),
    .B(_134_),
    .X(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _161_ (
    .A(_118_),
    .B(_135_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a31oi_1 _162_ (
    .A1(_118_),
    .A2(_117_),
    .A3(_134_),
    .B1(_119_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand4_1 _163_ (
    .A(_119_),
    .B(_118_),
    .C(_117_),
    .D(_134_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2b_1 _164_ (
    .A(_136_),
    .B_N(_137_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _165_ (
    .A(_120_),
    .B(_137_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _166_ (
    .A1(_130_),
    .A2(_137_),
    .B1(_129_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor3_1 _167_ (
    .A(_129_),
    .B(_130_),
    .C(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(_094_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xor2_1 _169_ (
    .A(_094_),
    .B(_138_),
    .X(_102_)
  );
  sky130_fd_sc_hd__nand3_1 _170_ (
    .A(_094_),
    .B(_095_),
    .C(_138_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__xnor2_1 _171_ (
    .A(_095_),
    .B(_139_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand4_1 _172_ (
    .A(_094_),
    .B(_095_),
    .C(_096_),
    .D(_138_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__xnor2_1 _173_ (
    .A(_096_),
    .B(_140_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _174_ (
    .A(_097_),
    .B(_141_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_096_),
    .B(_097_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__clkinv_1 _176_ (
    .A(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand4_1 _177_ (
    .A(_094_),
    .B(_095_),
    .C(_138_),
    .D(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(_098_),
    .B(_144_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand3_1 _179_ (
    .A(_094_),
    .B(_095_),
    .C(_098_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_142_),
    .B(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(_138_),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xnor2_1 _182_ (
    .A(_099_),
    .B(_147_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(_099_),
    .B(_100_),
    .C(_138_),
    .D(_146_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a31oi_1 _184_ (
    .A1(_099_),
    .A2(_138_),
    .A3(_146_),
    .B1(_100_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _185_ (
    .A(_148_),
    .SLEEP(_149_),
    .X(_108_)
  );
  sky130_fd_sc_hd__xnor2_1 _186_ (
    .A(_101_),
    .B(_148_),
    .Y(_109_)
  );
  assign mant_shift_output = mant_i[10:3];
  assign _114_ = mant_i[3];
  assign _112_ = mant_i[1];
  assign _110_ = mant_i[0];
  assign _113_ = mant_i[2];
  assign _111_ = mant_i[10];
  assign _120_ = mant_i[9];
  assign _119_ = mant_i[8];
  assign _118_ = mant_i[7];
  assign _117_ = mant_i[6];
  assign _116_ = mant_i[5];
  assign _115_ = mant_i[4];
  assign mant_o[0] = _121_;
  assign mant_o[1] = _122_;
  assign mant_o[2] = _123_;
  assign mant_o[3] = _124_;
  assign mant_o[4] = _125_;
  assign mant_o[5] = _126_;
  assign mant_o[6] = _127_;
  assign mant_o[7] = _128_;
  assign _094_ = exp_i[0];
  assign exp_o[0] = _102_;
  assign _095_ = exp_i[1];
  assign exp_o[1] = _103_;
  assign _096_ = exp_i[2];
  assign exp_o[2] = _104_;
  assign _097_ = exp_i[3];
  assign exp_o[3] = _105_;
  assign _098_ = exp_i[4];
  assign exp_o[4] = _106_;
  assign _099_ = exp_i[5];
  assign exp_o[5] = _107_;
  assign _100_ = exp_i[6];
  assign exp_o[6] = _108_;
  assign _101_ = exp_i[7];
  assign exp_o[7] = _109_;
endmodule
