/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/fractional_divider.v:4.1-194.10" *)
module fractional_divider(clk, rst, start, dividend, divisor, quotient, done);
  (* src = "src/fractional_divider.v:5.39-5.42" *)
  input clk;
  wire clk;
  (* src = "src/fractional_divider.v:6.40-6.43" *)
  input rst;
  wire rst;
  (* src = "src/fractional_divider.v:7.40-7.45" *)
  input start;
  wire start;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  input [10:0] dividend;
  wire [10:0] dividend;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  input [10:0] divisor;
  wire [10:0] divisor;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  output [10:0] quotient;
  wire [10:0] quotient;
  (* src = "src/fractional_divider.v:11.36-11.40" *)
  output done;
  wire done;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  (* src = "src/fractional_divider.v:19.23-19.30" *)
  wire _188_;
  (* src = "src/fractional_divider.v:19.23-19.30" *)
  wire _189_;
  (* src = "src/fractional_divider.v:19.23-19.30" *)
  wire _190_;
  (* src = "src/fractional_divider.v:19.23-19.30" *)
  wire _191_;
  (* src = "src/fractional_divider.v:19.23-19.30" *)
  wire _192_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _193_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _194_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _195_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _196_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _197_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _198_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _199_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _200_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _201_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _202_;
  (* src = "src/fractional_divider.v:8.48-8.56" *)
  wire _203_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _204_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _205_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _206_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _207_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _208_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _209_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _210_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _211_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _212_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _213_;
  (* src = "src/fractional_divider.v:9.48-9.55" *)
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  (* src = "src/fractional_divider.v:11.36-11.40" *)
  wire _226_;
  (* src = "src/fractional_divider.v:32.9-32.13" *)
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _335_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _336_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _337_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _338_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _339_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _340_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _341_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _342_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _343_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _344_;
  (* src = "src/fractional_divider.v:10.44-10.52" *)
  wire _345_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _346_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _347_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _348_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _349_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _350_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _351_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _352_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _353_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _354_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _355_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _356_;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire _357_;
  (* src = "src/fractional_divider.v:6.40-6.43" *)
  wire _358_;
  (* src = "src/fractional_divider.v:7.40-7.45" *)
  wire _359_;
  (* src = "src/fractional_divider.v:29.9-29.14" *)
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  (* src = "src/fractional_divider.v:31.9-31.18" *)
  wire clr_shift;
  (* src = "src/fractional_divider.v:19.23-19.30" *)
  wire [4:0] counter;
  wire [10:0] divisor_reg;
  (* src = "src/fractional_divider.v:36.9-36.19" *)
  wire en_counter;
  (* src = "src/fractional_divider.v:32.9-32.13" *)
  wire en_r;
  (* src = "src/fractional_divider.v:30.9-30.17" *)
  wire en_shift;
  (* src = "src/fractional_divider.v:33.9-33.13" *)
  wire en_y;
  (* src = "src/fractional_divider.v:23.15-23.28" *)
  wire [11:0] input_mux_out;
  (* src = "src/fractional_divider.v:26.10-26.13" *)
  wire ovf;
  wire [7:0] quotient_shift_reg;
  (* src = "src/fractional_divider.v:24.15-24.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10" *)
  wire [11:0] remainder_mux_out;
  (* src = "src/fractional_divider.v:15.15-15.28" *)
  wire [11:0] remainder_reg;
  (* src = "src/fractional_divider.v:34.9-34.15" *)
  wire sel_rx;
  (* src = "src/fractional_divider.v:29.9-29.14" *)
  wire state;
  sky130_fd_sc_hd__xnor2_1 _440_ (
    .A(_255_),
    .B(_258_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__nor2_1 _441_ (
    .A(_273_),
    .B(_314_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__a211oi_1 _442_ (
    .A1(_350_),
    .A2(_273_),
    .B1(_315_),
    .C1(_233_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__a21oi_1 _443_ (
    .A1(_197_),
    .A2(_233_),
    .B1(_236_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__o21ai_0 _444_ (
    .A1(_316_),
    .A2(_317_),
    .B1(_313_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(_350_),
    .B(_238_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__xnor2_1 _446_ (
    .A(_256_),
    .B(_257_),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nor2_1 _447_ (
    .A(_273_),
    .B(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__a211oi_1 _448_ (
    .A1(_349_),
    .A2(_273_),
    .B1(_320_),
    .C1(_233_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__a21oi_1 _449_ (
    .A1(_196_),
    .A2(_233_),
    .B1(_236_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__o21ai_0 _450_ (
    .A1(_321_),
    .A2(_322_),
    .B1(_318_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(_215_),
    .B(_272_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__a221oi_1 _452_ (
    .A1(_256_),
    .A2(_272_),
    .B1(_323_),
    .B2(_346_),
    .C1(_233_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__a21oi_1 _453_ (
    .A1(_195_),
    .A2(_233_),
    .B1(_236_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__o22ai_1 _454_ (
    .A1(_231_),
    .A2(_227_),
    .B1(_324_),
    .B2(_325_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a22o_1 _455_ (
    .A1(_193_),
    .A2(_233_),
    .B1(_238_),
    .B2(_346_),
    .X(_165_)
  );
  sky130_fd_sc_hd__and3_1 _456_ (
    .A(_189_),
    .B(_188_),
    .C(_360_),
    .X(_326_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(_190_),
    .B(_326_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__nand4_1 _458_ (
    .A(_191_),
    .B(_190_),
    .C(_189_),
    .D(_188_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__nor2_1 _459_ (
    .A(_360_),
    .B(_359_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__a21o_1 _460_ (
    .A1(_236_),
    .A2(_328_),
    .B1(_329_),
    .X(_330_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(_192_),
    .B(_330_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__o21ai_0 _462_ (
    .A1(_235_),
    .A2(_327_),
    .B1(_331_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21boi_0 _463_ (
    .A1(_232_),
    .A2(_327_),
    .B1_N(_330_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _464_ (
    .A(_190_),
    .B(_329_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__xor2_1 _465_ (
    .A(_190_),
    .B(_234_),
    .X(_333_)
  );
  sky130_fd_sc_hd__o21ai_0 _466_ (
    .A1(_237_),
    .A2(_333_),
    .B1(_332_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _467_ (
    .A1(_188_),
    .A2(_360_),
    .B1(_189_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__nor3_1 _468_ (
    .A(_233_),
    .B(_326_),
    .C(_334_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__mux2_1 _469_ (
    .A0(_360_),
    .A1(_329_),
    .S(_188_),
    .X(_160_)
  );
  sky130_fd_sc_hd__mux2_1 _470_ (
    .A0(_216_),
    .A1(_205_),
    .S(_233_),
    .X(_159_)
  );
  sky130_fd_sc_hd__mux2_1 _471_ (
    .A0(_225_),
    .A1(_214_),
    .S(_233_),
    .X(_158_)
  );
  sky130_fd_sc_hd__mux2_1 _472_ (
    .A0(_224_),
    .A1(_213_),
    .S(_233_),
    .X(_157_)
  );
  sky130_fd_sc_hd__mux2_1 _473_ (
    .A0(_223_),
    .A1(_212_),
    .S(_233_),
    .X(_156_)
  );
  sky130_fd_sc_hd__mux2_1 _474_ (
    .A0(_222_),
    .A1(_211_),
    .S(_233_),
    .X(_155_)
  );
  sky130_fd_sc_hd__mux2_1 _475_ (
    .A0(_221_),
    .A1(_210_),
    .S(_233_),
    .X(_154_)
  );
  sky130_fd_sc_hd__mux2_1 _476_ (
    .A0(_220_),
    .A1(_209_),
    .S(_233_),
    .X(_153_)
  );
  sky130_fd_sc_hd__mux2_1 _477_ (
    .A0(_219_),
    .A1(_208_),
    .S(_233_),
    .X(_152_)
  );
  sky130_fd_sc_hd__mux2_1 _478_ (
    .A0(_218_),
    .A1(_207_),
    .S(_233_),
    .X(_151_)
  );
  sky130_fd_sc_hd__mux2_1 _479_ (
    .A0(_217_),
    .A1(_206_),
    .S(_233_),
    .X(_150_)
  );
  sky130_fd_sc_hd__mux2_1 _480_ (
    .A0(_215_),
    .A1(_204_),
    .S(_233_),
    .X(_149_)
  );
  sky130_fd_sc_hd__clkinv_1 _481_ (
    .A(_358_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__clkinv_1 _482_ (
    .A(_358_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__clkinv_1 _483_ (
    .A(_358_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__clkinv_1 _484_ (
    .A(_358_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__clkinv_1 _485_ (
    .A(_358_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__clkinv_1 _486_ (
    .A(_358_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__clkinv_1 _487_ (
    .A(_358_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__clkinv_1 _488_ (
    .A(_358_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__clkinv_1 _489_ (
    .A(_358_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__clkinv_1 _490_ (
    .A(_358_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__clkinv_1 _491_ (
    .A(_358_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _492_ (
    .A(_358_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__clkinv_1 _493_ (
    .A(_358_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__clkinv_1 _494_ (
    .A(_358_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__clkinv_1 _495_ (
    .A(_358_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__clkinv_1 _496_ (
    .A(_358_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__clkinv_1 _497_ (
    .A(_358_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _498_ (
    .A(_358_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__clkinv_1 _499_ (
    .A(_358_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__clkinv_1 _500_ (
    .A(_358_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__clkinv_1 _501_ (
    .A(_358_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _502_ (
    .A(_358_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__clkinv_1 _503_ (
    .A(_358_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__clkinv_1 _504_ (
    .A(_358_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__clkinv_1 _505_ (
    .A(_358_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__clkinv_1 _506_ (
    .A(_358_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__clkinv_1 _507_ (
    .A(_358_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__clkinv_1 _508_ (
    .A(_358_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__clkinv_1 _509_ (
    .A(_358_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__clkinv_1 _510_ (
    .A(_358_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__clkinv_1 _511_ (
    .A(_358_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__clkinv_1 _512_ (
    .A(_358_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__clkinv_1 _513_ (
    .A(_358_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__clkinv_1 _514_ (
    .A(_358_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__clkinv_1 _515_ (
    .A(_358_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__clkinv_1 _516_ (
    .A(_358_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__clkinv_1 _517_ (
    .A(_358_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _518_ (
    .A(_358_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__clkinv_1 _519_ (
    .A(_358_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__clkinv_1 _520_ (
    .A(_347_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__clkinv_1 _521_ (
    .A(_357_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__clkinv_1 _522_ (
    .A(_352_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__clkinv_1 _523_ (
    .A(_349_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__clkinv_1 _524_ (
    .A(_191_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__clkinv_1 _525_ (
    .A(_358_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _526_ (
    .A(_359_),
    .SLEEP(_360_),
    .X(_233_)
  );
  sky130_fd_sc_hd__nand2_1 _527_ (
    .A(_189_),
    .B(_188_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand2b_1 _528_ (
    .A_N(_192_),
    .B(_191_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor3_1 _529_ (
    .A(_190_),
    .B(_234_),
    .C(_235_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _530_ (
    .A(_360_),
    .SLEEP(_226_),
    .X(_236_)
  );
  sky130_fd_sc_hd__nand2b_1 _531_ (
    .A_N(_226_),
    .B(_360_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _532_ (
    .A(_233_),
    .B(_236_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__clkinv_1 _533_ (
    .A(_238_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a22o_1 _534_ (
    .A1(_345_),
    .A2(_236_),
    .B1(_238_),
    .B2(_336_),
    .X(_187_)
  );
  sky130_fd_sc_hd__a22o_1 _535_ (
    .A1(_344_),
    .A2(_236_),
    .B1(_238_),
    .B2(_345_),
    .X(_186_)
  );
  sky130_fd_sc_hd__a22o_1 _536_ (
    .A1(_343_),
    .A2(_236_),
    .B1(_238_),
    .B2(_344_),
    .X(_185_)
  );
  sky130_fd_sc_hd__a22o_1 _537_ (
    .A1(_342_),
    .A2(_236_),
    .B1(_238_),
    .B2(_343_),
    .X(_184_)
  );
  sky130_fd_sc_hd__a22o_1 _538_ (
    .A1(_341_),
    .A2(_236_),
    .B1(_238_),
    .B2(_342_),
    .X(_183_)
  );
  sky130_fd_sc_hd__a22o_1 _539_ (
    .A1(_340_),
    .A2(_236_),
    .B1(_238_),
    .B2(_341_),
    .X(_182_)
  );
  sky130_fd_sc_hd__a22o_1 _540_ (
    .A1(_339_),
    .A2(_236_),
    .B1(_238_),
    .B2(_340_),
    .X(_181_)
  );
  sky130_fd_sc_hd__a22o_1 _541_ (
    .A1(_338_),
    .A2(_236_),
    .B1(_238_),
    .B2(_339_),
    .X(_180_)
  );
  sky130_fd_sc_hd__a22o_1 _542_ (
    .A1(_337_),
    .A2(_236_),
    .B1(_238_),
    .B2(_338_),
    .X(_179_)
  );
  sky130_fd_sc_hd__a22o_1 _543_ (
    .A1(_335_),
    .A2(_236_),
    .B1(_238_),
    .B2(_337_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _544_ (
    .A(_335_),
    .B(_238_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__xor2_1 _545_ (
    .A(_357_),
    .B(_225_),
    .X(_240_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _546_ (
    .A(_356_),
    .SLEEP(_224_),
    .X(_241_)
  );
  sky130_fd_sc_hd__xnor2_1 _547_ (
    .A(_356_),
    .B(_224_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand2b_1 _548_ (
    .A_N(_223_),
    .B(_355_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2b_1 _549_ (
    .A_N(_355_),
    .B(_223_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nand2b_1 _550_ (
    .A_N(_222_),
    .B(_354_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _551_ (
    .A(_222_),
    .SLEEP(_354_),
    .X(_246_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _552_ (
    .A(_245_),
    .SLEEP(_246_),
    .X(_247_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _553_ (
    .A(_353_),
    .SLEEP(_221_),
    .X(_248_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _554_ (
    .A(_221_),
    .SLEEP(_353_),
    .X(_249_)
  );
  sky130_fd_sc_hd__nor2_1 _555_ (
    .A(_230_),
    .B(_220_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__xnor2_1 _556_ (
    .A(_352_),
    .B(_220_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nand2b_1 _557_ (
    .A_N(_219_),
    .B(_351_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand2b_1 _558_ (
    .A_N(_351_),
    .B(_219_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nand2b_1 _559_ (
    .A_N(_218_),
    .B(_350_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__xor2_1 _560_ (
    .A(_350_),
    .B(_218_),
    .X(_255_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _561_ (
    .A(_215_),
    .SLEEP(_346_),
    .X(_256_)
  );
  sky130_fd_sc_hd__xor2_1 _562_ (
    .A(_349_),
    .B(_217_),
    .X(_257_)
  );
  sky130_fd_sc_hd__maj3_1 _563_ (
    .A(_231_),
    .B(_217_),
    .C(_256_),
    .X(_258_)
  );
  sky130_fd_sc_hd__o21ai_0 _564_ (
    .A1(_255_),
    .A2(_258_),
    .B1(_254_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__o211ai_1 _565_ (
    .A1(_255_),
    .A2(_258_),
    .B1(_252_),
    .C1(_254_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand3_1 _566_ (
    .A(_251_),
    .B(_253_),
    .C(_260_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o21ai_0 _567_ (
    .A1(_230_),
    .A2(_220_),
    .B1(_261_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__a311oi_1 _568_ (
    .A1(_251_),
    .A2(_253_),
    .A3(_260_),
    .B1(_250_),
    .C1(_248_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _569_ (
    .A(_249_),
    .SLEEP(_263_),
    .X(_264_)
  );
  sky130_fd_sc_hd__o21ai_0 _570_ (
    .A1(_246_),
    .A2(_264_),
    .B1(_245_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__o311ai_0 _571_ (
    .A1(_246_),
    .A2(_249_),
    .A3(_263_),
    .B1(_245_),
    .C1(_243_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__and3_1 _572_ (
    .A(_242_),
    .B(_244_),
    .C(_266_),
    .X(_267_)
  );
  sky130_fd_sc_hd__a31oi_1 _573_ (
    .A1(_242_),
    .A2(_244_),
    .A3(_266_),
    .B1(_241_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__maj3_1 _574_ (
    .A(_229_),
    .B(_225_),
    .C(_268_),
    .X(_269_)
  );
  sky130_fd_sc_hd__xor2_1 _575_ (
    .A(_347_),
    .B(_216_),
    .X(_270_)
  );
  sky130_fd_sc_hd__maj3_1 _576_ (
    .A(_228_),
    .B(_216_),
    .C(_269_),
    .X(_271_)
  );
  sky130_fd_sc_hd__xnor2_1 _577_ (
    .A(_348_),
    .B(_271_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__xor2_1 _578_ (
    .A(_348_),
    .B(_271_),
    .X(_273_)
  );
  sky130_fd_sc_hd__o21ai_0 _579_ (
    .A1(_237_),
    .A2(_273_),
    .B1(_239_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _580_ (
    .A(_228_),
    .B(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__xnor2_1 _581_ (
    .A(_269_),
    .B(_270_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a21oi_1 _582_ (
    .A1(_272_),
    .A2(_275_),
    .B1(_237_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__a22o_1 _583_ (
    .A1(_348_),
    .A2(_238_),
    .B1(_274_),
    .B2(_276_),
    .X(_176_)
  );
  sky130_fd_sc_hd__xnor2_1 _584_ (
    .A(_240_),
    .B(_268_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nor2_1 _585_ (
    .A(_273_),
    .B(_277_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a211oi_1 _586_ (
    .A1(_357_),
    .A2(_273_),
    .B1(_278_),
    .C1(_233_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__a21oi_1 _587_ (
    .A1(_194_),
    .A2(_233_),
    .B1(_236_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__o22ai_1 _588_ (
    .A1(_228_),
    .A2(_227_),
    .B1(_279_),
    .B2(_280_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _589_ (
    .A1(_244_),
    .A2(_266_),
    .B1(_242_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nor2_1 _590_ (
    .A(_267_),
    .B(_281_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__a21oi_1 _591_ (
    .A1(_272_),
    .A2(_282_),
    .B1(_233_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__a21boi_0 _592_ (
    .A1(_356_),
    .A2(_273_),
    .B1_N(_283_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__a21oi_1 _593_ (
    .A1(_203_),
    .A2(_233_),
    .B1(_236_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__o22ai_1 _594_ (
    .A1(_229_),
    .A2(_227_),
    .B1(_284_),
    .B2(_285_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _595_ (
    .A(_356_),
    .B(_238_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__and2_0 _596_ (
    .A(_243_),
    .B(_244_),
    .X(_287_)
  );
  sky130_fd_sc_hd__xnor2_1 _597_ (
    .A(_265_),
    .B(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__nor2_1 _598_ (
    .A(_273_),
    .B(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__a211oi_1 _599_ (
    .A1(_355_),
    .A2(_273_),
    .B1(_289_),
    .C1(_233_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__a21oi_1 _600_ (
    .A1(_202_),
    .A2(_233_),
    .B1(_236_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__o21ai_0 _601_ (
    .A1(_290_),
    .A2(_291_),
    .B1(_286_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _602_ (
    .A(_355_),
    .B(_238_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__xor2_1 _603_ (
    .A(_247_),
    .B(_264_),
    .X(_293_)
  );
  sky130_fd_sc_hd__nor2_1 _604_ (
    .A(_273_),
    .B(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__a211oi_1 _605_ (
    .A1(_354_),
    .A2(_273_),
    .B1(_294_),
    .C1(_233_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__a21oi_1 _606_ (
    .A1(_201_),
    .A2(_233_),
    .B1(_236_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__o21ai_0 _607_ (
    .A1(_295_),
    .A2(_296_),
    .B1(_292_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand2_1 _608_ (
    .A(_354_),
    .B(_238_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__nor2_1 _609_ (
    .A(_248_),
    .B(_249_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__xnor2_1 _610_ (
    .A(_262_),
    .B(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__nor2_1 _611_ (
    .A(_273_),
    .B(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__a211oi_1 _612_ (
    .A1(_353_),
    .A2(_273_),
    .B1(_300_),
    .C1(_233_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__a21oi_1 _613_ (
    .A1(_200_),
    .A2(_233_),
    .B1(_236_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__o21ai_0 _614_ (
    .A1(_301_),
    .A2(_302_),
    .B1(_297_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _615_ (
    .A(_353_),
    .B(_238_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__a21oi_1 _616_ (
    .A1(_253_),
    .A2(_260_),
    .B1(_251_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__nor3b_1 _617_ (
    .A(_273_),
    .B(_304_),
    .C_N(_261_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__a211oi_1 _618_ (
    .A1(_352_),
    .A2(_273_),
    .B1(_305_),
    .C1(_233_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__a21oi_1 _619_ (
    .A1(_199_),
    .A2(_233_),
    .B1(_236_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__o21ai_0 _620_ (
    .A1(_306_),
    .A2(_307_),
    .B1(_303_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _621_ (
    .A(_252_),
    .B(_253_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__xor2_1 _622_ (
    .A(_259_),
    .B(_308_),
    .X(_309_)
  );
  sky130_fd_sc_hd__nor2_1 _623_ (
    .A(_273_),
    .B(_309_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__a211oi_1 _624_ (
    .A1(_351_),
    .A2(_273_),
    .B1(_310_),
    .C1(_233_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__a21oi_1 _625_ (
    .A1(_198_),
    .A2(_233_),
    .B1(_236_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__o22ai_1 _626_ (
    .A1(_230_),
    .A2(_227_),
    .B1(_311_),
    .B2(_312_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _627_ (
    .A(_351_),
    .B(_238_),
    .Y(_313_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(clk),
    .D(_401_),
    .Q(divisor_reg[0]),
    .RESET_B(_361_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(clk),
    .D(_402_),
    .Q(divisor_reg[1]),
    .RESET_B(_362_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _630_ (
    .CLK(clk),
    .D(_403_),
    .Q(divisor_reg[2]),
    .RESET_B(_363_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _631_ (
    .CLK(clk),
    .D(_404_),
    .Q(divisor_reg[3]),
    .RESET_B(_364_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _632_ (
    .CLK(clk),
    .D(_405_),
    .Q(divisor_reg[4]),
    .RESET_B(_365_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _633_ (
    .CLK(clk),
    .D(_406_),
    .Q(divisor_reg[5]),
    .RESET_B(_366_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _634_ (
    .CLK(clk),
    .D(_407_),
    .Q(divisor_reg[6]),
    .RESET_B(_367_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _635_ (
    .CLK(clk),
    .D(_408_),
    .Q(divisor_reg[7]),
    .RESET_B(_368_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _636_ (
    .CLK(clk),
    .D(_409_),
    .Q(divisor_reg[8]),
    .RESET_B(_369_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _637_ (
    .CLK(clk),
    .D(_410_),
    .Q(divisor_reg[9]),
    .RESET_B(_370_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _638_ (
    .CLK(clk),
    .D(_411_),
    .Q(divisor_reg[10]),
    .RESET_B(_371_)
  );
  (* src = "src/fractional_divider.v:173.5-186.8" *)
  sky130_fd_sc_hd__dfrtp_1 _639_ (
    .CLK(clk),
    .D(_412_),
    .Q(counter[0]),
    .RESET_B(_372_)
  );
  (* src = "src/fractional_divider.v:173.5-186.8" *)
  sky130_fd_sc_hd__dfrtp_1 _640_ (
    .CLK(clk),
    .D(_413_),
    .Q(counter[1]),
    .RESET_B(_373_)
  );
  (* src = "src/fractional_divider.v:173.5-186.8" *)
  sky130_fd_sc_hd__dfrtp_1 _641_ (
    .CLK(clk),
    .D(_414_),
    .Q(counter[2]),
    .RESET_B(_374_)
  );
  (* src = "src/fractional_divider.v:173.5-186.8" *)
  sky130_fd_sc_hd__dfrtp_1 _642_ (
    .CLK(clk),
    .D(_415_),
    .Q(counter[3]),
    .RESET_B(_375_)
  );
  (* src = "src/fractional_divider.v:173.5-186.8" *)
  sky130_fd_sc_hd__dfrtp_1 _643_ (
    .CLK(clk),
    .D(_416_),
    .Q(counter[4]),
    .RESET_B(_376_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _644_ (
    .CLK(clk),
    .D(_417_),
    .Q(remainder_reg[0]),
    .RESET_B(_377_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _645_ (
    .CLK(clk),
    .D(_418_),
    .Q(remainder_reg[1]),
    .RESET_B(_378_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _646_ (
    .CLK(clk),
    .D(_419_),
    .Q(remainder_reg[2]),
    .RESET_B(_379_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _647_ (
    .CLK(clk),
    .D(_420_),
    .Q(remainder_reg[3]),
    .RESET_B(_380_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _648_ (
    .CLK(clk),
    .D(_421_),
    .Q(remainder_reg[4]),
    .RESET_B(_381_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _649_ (
    .CLK(clk),
    .D(_422_),
    .Q(remainder_reg[5]),
    .RESET_B(_382_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _650_ (
    .CLK(clk),
    .D(_423_),
    .Q(remainder_reg[6]),
    .RESET_B(_383_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _651_ (
    .CLK(clk),
    .D(_424_),
    .Q(remainder_reg[7]),
    .RESET_B(_384_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _652_ (
    .CLK(clk),
    .D(_425_),
    .Q(remainder_reg[8]),
    .RESET_B(_385_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _653_ (
    .CLK(clk),
    .D(_426_),
    .Q(remainder_reg[9]),
    .RESET_B(_386_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _654_ (
    .CLK(clk),
    .D(_427_),
    .Q(remainder_reg[10]),
    .RESET_B(_387_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _655_ (
    .CLK(clk),
    .D(_428_),
    .Q(remainder_reg[11]),
    .RESET_B(_388_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _656_ (
    .CLK(clk),
    .D(_429_),
    .Q(quotient[0]),
    .RESET_B(_389_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _657_ (
    .CLK(clk),
    .D(_430_),
    .Q(quotient[1]),
    .RESET_B(_390_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _658_ (
    .CLK(clk),
    .D(_431_),
    .Q(quotient[2]),
    .RESET_B(_391_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _659_ (
    .CLK(clk),
    .D(_432_),
    .Q(quotient[3]),
    .RESET_B(_392_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _660_ (
    .CLK(clk),
    .D(_433_),
    .Q(quotient[4]),
    .RESET_B(_393_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _661_ (
    .CLK(clk),
    .D(_434_),
    .Q(quotient[5]),
    .RESET_B(_394_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _662_ (
    .CLK(clk),
    .D(_435_),
    .Q(quotient[6]),
    .RESET_B(_395_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _663_ (
    .CLK(clk),
    .D(_436_),
    .Q(quotient[7]),
    .RESET_B(_396_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _664_ (
    .CLK(clk),
    .D(_437_),
    .Q(quotient[8]),
    .RESET_B(_397_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _665_ (
    .CLK(clk),
    .D(_438_),
    .Q(quotient[9]),
    .RESET_B(_398_)
  );
  (* src = "src/fractional_divider.v:43.5-69.8" *)
  sky130_fd_sc_hd__dfrtp_1 _666_ (
    .CLK(clk),
    .D(_439_),
    .Q(quotient[10]),
    .RESET_B(_399_)
  );
  (* src = "src/fractional_divider.v:81.5-107.8" *)
  sky130_fd_sc_hd__dfrtp_1 _667_ (
    .CLK(clk),
    .D(en_r),
    .Q(state),
    .RESET_B(_400_)
  );
  assign en_shift = en_r;
  assign en_y = clr_shift;
  assign ovf = done;
  assign quotient_shift_reg = quotient[7:0];
  assign remainder_mux_out[11] = 1'hx;
  assign sel_rx = clr_shift;
  assign _336_ = quotient[10];
  assign en_r = _227_;
  assign _439_ = _187_;
  assign _345_ = quotient[9];
  assign _438_ = _186_;
  assign _344_ = quotient[8];
  assign _437_ = _185_;
  assign _343_ = quotient[7];
  assign _436_ = _184_;
  assign _342_ = quotient[6];
  assign _435_ = _183_;
  assign _341_ = quotient[5];
  assign _434_ = _182_;
  assign _340_ = quotient[4];
  assign _433_ = _181_;
  assign _339_ = quotient[3];
  assign _432_ = _180_;
  assign _338_ = quotient[2];
  assign _431_ = _179_;
  assign _337_ = quotient[1];
  assign _430_ = _178_;
  assign _335_ = quotient[0];
  assign _429_ = _177_;
  assign _348_ = remainder_reg[11];
  assign _428_ = _176_;
  assign _347_ = remainder_reg[10];
  assign _427_ = _175_;
  assign _357_ = remainder_reg[9];
  assign _426_ = _174_;
  assign _356_ = remainder_reg[8];
  assign _425_ = _173_;
  assign _355_ = remainder_reg[7];
  assign _424_ = _172_;
  assign _354_ = remainder_reg[6];
  assign _423_ = _171_;
  assign _353_ = remainder_reg[5];
  assign _422_ = _170_;
  assign _352_ = remainder_reg[4];
  assign _421_ = _169_;
  assign _351_ = remainder_reg[3];
  assign _420_ = _168_;
  assign _350_ = remainder_reg[2];
  assign _419_ = _167_;
  assign _349_ = remainder_reg[1];
  assign _418_ = _166_;
  assign _346_ = remainder_reg[0];
  assign _417_ = _165_;
  assign _192_ = counter[4];
  assign _416_ = _164_;
  assign _191_ = counter[3];
  assign _415_ = _163_;
  assign _190_ = counter[2];
  assign _414_ = _162_;
  assign _189_ = counter[1];
  assign _413_ = _161_;
  assign _188_ = counter[0];
  assign _412_ = _160_;
  assign _216_ = divisor_reg[10];
  assign _205_ = divisor[10];
  assign _411_ = _159_;
  assign _225_ = divisor_reg[9];
  assign _214_ = divisor[9];
  assign _410_ = _158_;
  assign _224_ = divisor_reg[8];
  assign _213_ = divisor[8];
  assign _409_ = _157_;
  assign _223_ = divisor_reg[7];
  assign _212_ = divisor[7];
  assign _408_ = _156_;
  assign _222_ = divisor_reg[6];
  assign _211_ = divisor[6];
  assign _407_ = _155_;
  assign _221_ = divisor_reg[5];
  assign _210_ = divisor[5];
  assign _406_ = _154_;
  assign _220_ = divisor_reg[4];
  assign _209_ = divisor[4];
  assign _405_ = _153_;
  assign _219_ = divisor_reg[3];
  assign _208_ = divisor[3];
  assign _404_ = _152_;
  assign _218_ = divisor_reg[2];
  assign _207_ = divisor[2];
  assign _403_ = _151_;
  assign _217_ = divisor_reg[1];
  assign _206_ = divisor[1];
  assign _402_ = _150_;
  assign _215_ = divisor_reg[0];
  assign _204_ = divisor[0];
  assign _401_ = _149_;
  assign _360_ = state;
  assign _359_ = start;
  assign done = _226_;
  assign _193_ = dividend[0];
  assign _195_ = dividend[1];
  assign _196_ = dividend[2];
  assign _197_ = dividend[3];
  assign _198_ = dividend[4];
  assign _199_ = dividend[5];
  assign _200_ = dividend[6];
  assign _201_ = dividend[7];
  assign _202_ = dividend[8];
  assign _203_ = dividend[9];
  assign _194_ = dividend[10];
  assign _358_ = rst;
  assign _361_ = _109_;
  assign _362_ = _110_;
  assign _363_ = _111_;
  assign _364_ = _112_;
  assign _365_ = _113_;
  assign _366_ = _114_;
  assign _367_ = _115_;
  assign _368_ = _116_;
  assign _369_ = _117_;
  assign _370_ = _118_;
  assign _371_ = _119_;
  assign _372_ = _120_;
  assign _373_ = _121_;
  assign _374_ = _122_;
  assign _375_ = _123_;
  assign _376_ = _124_;
  assign _377_ = _125_;
  assign _378_ = _126_;
  assign _379_ = _127_;
  assign _380_ = _128_;
  assign _381_ = _129_;
  assign _382_ = _130_;
  assign _383_ = _131_;
  assign _384_ = _132_;
  assign _385_ = _133_;
  assign _386_ = _134_;
  assign _387_ = _135_;
  assign _388_ = _136_;
  assign _389_ = _137_;
  assign _390_ = _138_;
  assign _391_ = _139_;
  assign _392_ = _140_;
  assign _393_ = _141_;
  assign _394_ = _142_;
  assign _395_ = _143_;
  assign _396_ = _144_;
  assign _397_ = _145_;
  assign _398_ = _146_;
  assign _399_ = _147_;
  assign _400_ = _148_;
endmodule
